name       : nanorc
version    : 2020.10.10
release    : 1
source     :
    - https://github.com/scopatz/nanorc/releases/download/2020.10.10/nanorc-2020.10.10.tar.gz : cd674e9eb230e4ba306b418c22d1891d93a3d2ffdf22234748d3398da50dfe64
license    : GPL-3.0-or-later
component  : system.devel
summary    : Improved Nano Syntax Highlighting Files
description: |
    Package with language-specific nanorc files that have improved definitions of syntax highlighting.
install    : |
    install -dDm755 $installdir/usr/share/nanorc
    find $workdir -name "*.nanorc" | xargs install -Dm644 -t $installdir/usr/share/nanorc