name       : nanorc
version    : 2020.10.10
release    : 2
source     :
    - git|https://github.com/scopatz/nanorc.git : 1aa64a86cf4c750e4d4788ef1a19d7a71ab641dd
license    : GPL-3.0-or-later
component  : system.devel
summary    : Improved Nano Syntax Highlighting Files
description: |
    Package with language-specific nanorc files that have improved definitions of syntax highlighting.
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-git-commit-colours-for-dark-terminals.patch
install    : |
    install -dDm755 $installdir/usr/share/nanorc
    find $workdir -name "*.nanorc" | xargs install -Dm644 -t $installdir/usr/share/nanorc
